/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const MessageType = IDL.Variant({
  'other' : IDL.Null,
  'request' : IDL.Null,
  'inquiry' : IDL.Null,
  'feedback' : IDL.Null,
});
export const ContactSubmission = IDL.Record({
  'name' : IDL.Text,
  'sender' : IDL.Principal,
  'email' : IDL.Text,
  'messageType' : MessageType,
  'message' : IDL.Text,
});

export const idlService = IDL.Service({
  'clearSubmissions' : IDL.Func([], [], []),
  'getAllSubmissions' : IDL.Func([], [IDL.Vec(ContactSubmission)], ['query']),
  'submitContactForm' : IDL.Func(
      [IDL.Text, IDL.Text, MessageType, IDL.Text],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const MessageType = IDL.Variant({
    'other' : IDL.Null,
    'request' : IDL.Null,
    'inquiry' : IDL.Null,
    'feedback' : IDL.Null,
  });
  const ContactSubmission = IDL.Record({
    'name' : IDL.Text,
    'sender' : IDL.Principal,
    'email' : IDL.Text,
    'messageType' : MessageType,
    'message' : IDL.Text,
  });
  
  return IDL.Service({
    'clearSubmissions' : IDL.Func([], [], []),
    'getAllSubmissions' : IDL.Func([], [IDL.Vec(ContactSubmission)], ['query']),
    'submitContactForm' : IDL.Func(
        [IDL.Text, IDL.Text, MessageType, IDL.Text],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };